select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `pedidos` (`id` bigint unsigned not null auto_increment primary key, `pieza_id` bigint unsigned null, `nombre` varchar(255) null, `cantidad` int null, `senia` decimal(10, 2) null, `minimo` decimal(10, 2) null, `fecha` datetime null, `estado` enum('A pedir', 'Pedido') null, `observacion` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `pedidos` add constraint `pedidos_pieza_id_foreign` foreign key (`pieza_id`) references `piezas` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_08_31_194912_create_pedidos_table', 16);
