select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `clientes` (`id` bigint unsigned not null auto_increment primary key, `nombre` varchar(255) null, `documento` varchar(20) not null, `cuil` varchar(13) null, `nacimiento` datetime null, `estado_civil` enum('Soltero/a', 'Casado/a', 'Divorciado/a', 'Concubino/a', 'Viudo/a') null, `email` varchar(255) null, `particular_area` varchar(10) null, `particular` varchar(30) null, `celular_area` varchar(10) null, `celular` varchar(30) null, `calle` varchar(50) null, `nro` varchar(10) null, `piso` varchar(10) null, `depto` varchar(10) null, `localidad_id` bigint unsigned null, `cp` varchar(10) null, `nacionalidad` varchar(255) null, `ocupacion` varchar(255) null, `trabajo` varchar(255) null, `iva` enum('Responsable Inscripto', 'Responsable No inscripto', 'No Inscripto', 'Monotributista', 'Consumidor Final') null, `llego` enum('Google', 'Diario', 'Recomendado', 'Radio', 'Ya compró', 'Página Web', 'Ya conocía', 'Mercado Libre', 'Otro') null, `foto` text null, `observaciones` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `localidads` (`id` bigint unsigned not null auto_increment primary key, `nombre` varchar(255) null, `provincia_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `localidads` add constraint `localidads_provincia_id_foreign` foreign key (`provincia_id`) references `provincias` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_04_29_191024_create_localidads_table', 4);
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `clientes` (`id` bigint unsigned not null auto_increment primary key, `nombre` varchar(255) null, `documento` varchar(20) not null, `cuil` varchar(13) null, `nacimiento` datetime null, `estado_civil` enum('Soltero/a', 'Casado/a', 'Divorciado/a', 'Concubino/a', 'Viudo/a') null, `email` varchar(255) null, `particular_area` varchar(10) null, `particular` varchar(30) null, `celular_area` varchar(10) null, `celular` varchar(30) null, `calle` varchar(50) null, `nro` varchar(10) null, `piso` varchar(10) null, `depto` varchar(10) null, `localidad_id` bigint unsigned null, `cp` varchar(10) null, `nacionalidad` varchar(255) null, `ocupacion` varchar(255) null, `trabajo` varchar(255) null, `iva` enum('Responsable Inscripto', 'Responsable No inscripto', 'No Inscripto', 'Monotributista', 'Consumidor Final') null, `llego` enum('Google', 'Diario', 'Recomendado', 'Radio', 'Ya compró', 'Página Web', 'Ya conocía', 'Mercado Libre', 'Otro') null, `foto` text null, `observaciones` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `clientes` add constraint `clientes_localidad_id_foreign` foreign key (`localidad_id`) references `localidads` (`id`);
alter table `clientes` add unique `clientes_documento_unique`(`documento`);
insert into `migrations` (`migration`, `batch`) values ('2025_04_29_185935_create_clientes_table', 5);
