select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
alter table `piezas` add `ubicacion_id` bigint unsigned null;
alter table `piezas` add constraint `piezas_ubicacion_id_foreign` foreign key (`ubicacion_id`) references `ubicacions` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_11_29_101427_add_ubicacion_to_piezas_table', 24);
create table `pieza_ubicacion` (`id` bigint unsigned not null auto_increment primary key, `pieza_id` bigint unsigned not null, `ubicacion_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
select column_name as `column_name` from information_schema.columns where table_schema = 'lv_kaizen' and table_name = 'piezas';
alter table `piezas` drop foreign key `piezas_ubicacion_id_foreign`;
alter table `piezas` drop `ubicacion_id`;
insert into `migrations` (`migration`, `batch`) values ('2025_12_01_205549_remove_ubicacion_id_from_piezas', 25);
create table `proveedors` (`id` bigint unsigned not null auto_increment primary key, `nombre` varchar(255) null, `razon` varchar(255) null, `cuil` varchar(13) null, `email` varchar(255) null, `particular_area` varchar(10) null, `particular` varchar(30) null, `celular_area` varchar(10) null, `celular` varchar(30) null, `iva` enum('Responsable Inscripto', 'Responsable No inscripto', 'No Inscripto', 'Monotributista', 'Consumidor Final') null, `observaciones` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
insert into `migrations` (`migration`, `batch`) values ('2025_12_11_105630_create_proveedors_table', 25);
create table `movimiento_piezas` (`id` bigint unsigned not null auto_increment primary key, `sucursal_origen_id` bigint unsigned null, `sucursal_destino_id` bigint unsigned null, `user_id` bigint unsigned not null, `fecha` datetime null, `observaciones` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `movimiento_piezas` add constraint `movimiento_piezas_sucursal_origen_id_foreign` foreign key (`sucursal_origen_id`) references `sucursals` (`id`);
alter table `movimiento_piezas` add constraint `movimiento_piezas_sucursal_destino_id_foreign` foreign key (`sucursal_destino_id`) references `sucursals` (`id`);
alter table `movimiento_piezas` add constraint `movimiento_piezas_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
insert into `migrations` (`migration`, `batch`) values ('2025_12_12_102729_create_movimiento_piezas_table', 25);
alter table `venta_piezas` add `cliente_id` bigint unsigned null;
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
