select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `ventas` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `user_name` varchar(255) null, `cliente_id` bigint unsigned null, `sucursal_id` bigint unsigned null, `unidad_id` bigint unsigned null, `monto` decimal(10, 2) null, `total` decimal(10, 2) null, `fecha` datetime null, `forma` enum('Contado', 'Crédito') null, `observacion` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `ventas` add constraint `ventas_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
alter table `ventas` add constraint `ventas_cliente_id_foreign` foreign key (`cliente_id`) references `clientes` (`id`);
alter table `ventas` add constraint `ventas_sucursal_id_foreign` foreign key (`sucursal_id`) references `sucursals` (`id`);
alter table `ventas` add constraint `ventas_unidad_id_foreign` foreign key (`unidad_id`) references `unidads` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_08_19_085037_create_ventas_table', 15);
create table `autorizacions` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `user_name` varchar(255) null, `unidad_id` bigint unsigned null, `fecha` datetime null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `autorizacions` add constraint `autorizacions_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
alter table `autorizacions` add constraint `autorizacions_unidad_id_foreign` foreign key (`unidad_id`) references `unidads` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_08_19_094126_create_autorizacions_table', 15);
create table `pagos` (`id` bigint unsigned not null auto_increment primary key, `venta_id` bigint unsigned null, `entidad_id` bigint unsigned null, `monto` decimal(10, 2) null, `fecha` datetime null, `pagado` decimal(10, 2) null, `contadora` datetime null, `detalle` text null, `observacion` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `pagos` add constraint `pagos_venta_id_foreign` foreign key (`venta_id`) references `ventas` (`id`);
alter table `pagos` add constraint `pagos_entidad_id_foreign` foreign key (`entidad_id`) references `entidads` (`id`);
insert into `migrations` (`migration`, `batch`) values ('2025_08_19_094140_create_pagos_table', 15);
