select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
create table `ubicacions` (`id` bigint unsigned not null auto_increment primary key, `sucursal_id` bigint unsigned not null, `nombre` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `ubicacions` add constraint `ubicacions_sucursal_id_foreign` foreign key (`sucursal_id`) references `sucursals` (`id`);
alter table `piezas` add `ubicacion_id` bigint unsigned null;
alter table `piezas` add constraint `piezas_ubicacion_id_foreign` foreign key (`ubicacion_id`) references `ubicacions` (`id`);
create table `pieza_ubicacion` (`id` bigint unsigned not null auto_increment primary key, `pieza_id` bigint unsigned not null, `ubicacion_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `pieza_ubicacion` add constraint `pieza_ubicacion_pieza_id_foreign` foreign key (`pieza_id`) references `piezas` (`id`) on delete cascade;
alter table `pieza_ubicacion` add constraint `pieza_ubicacion_ubicacion_id_foreign` foreign key (`ubicacion_id`) references `ubicacions` (`id`) on delete cascade;
select column_name as `column_name` from information_schema.columns where table_schema = 'lv_kaizen' and table_name = 'piezas';
