select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select * from information_schema.tables where table_schema = 'lv_kaizen' and table_name = 'migrations' and table_type = 'BASE TABLE';
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select `migration` from `migrations` order by `batch` asc, `migration` asc;
select max(`batch`) as aggregate from `migrations`;
alter table `venta_piezas` add `cliente_id` bigint unsigned null;
alter table `venta_piezas` add constraint `venta_piezas_cliente_id_foreign` foreign key (`cliente_id`) references `clientes` (`id`);
alter table `movimiento_piezas` add `estado` varchar(255) not null default 'Pendiente', add `aceptado` timestamp null, add `user_acepta_id` bigint unsigned null;
alter table `movimiento_piezas` add constraint `movimiento_piezas_user_acepta_id_foreign` foreign key (`user_acepta_id`) references `users` (`id`);
alter table `movimientos` add `estado` varchar(255) not null default 'Pendiente', add `aceptado` timestamp null, add `user_acepta_id` bigint unsigned null;
alter table `movimientos` add constraint `movimientos_user_acepta_id_foreign` foreign key (`user_acepta_id`) references `users` (`id`);
alter table `servicios` add `obra` decimal(12, 2) null, add `monto_repuestos` decimal(12, 2) null;
alter table `venta_piezas` add `servicio_id` bigint unsigned null after `pedido`;
alter table `venta_piezas` add constraint `venta_piezas_servicio_id_foreign` foreign key (`servicio_id`) references `servicios` (`id`) on delete set null;
alter table `pagos` add `servicio_id` bigint unsigned null after `venta_id`;
alter table `pagos` add constraint `pagos_servicio_id_foreign` foreign key (`servicio_id`) references `servicios` (`id`) on delete set null;
alter table `servicios` add `forma` enum('Contado', 'Crédito') null after `costo_repuestos`;
alter table `servicios` add `marca_id` bigint unsigned null, add `modelo_id` bigint unsigned null;
alter table `servicios` add constraint `servicios_marca_id_foreign` foreign key (`marca_id`) references `marcas` (`id`);
alter table `servicios` add constraint `servicios_modelo_id_foreign` foreign key (`modelo_id`) references `modelos` (`id`);
alter table `entidads` add `forma` enum('Contado', 'Crédito') null;
alter table `pagos` add `venta_pieza_id` bigint unsigned null;
alter table `pagos` add constraint `pagos_venta_pieza_id_foreign` foreign key (`venta_pieza_id`) references `venta_piezas` (`id`);
alter table `venta_piezas` add `forma` varchar(255) null after `destino`;
alter table `movimiento_cajas` add `servicio_id` bigint unsigned null after `venta_id`, add `venta_pieza_id` bigint unsigned null after `servicio_id`;
alter table `movimiento_cajas` add constraint `movimiento_cajas_servicio_id_foreign` foreign key (`servicio_id`) references `servicios` (`id`) on delete set null;
alter table `movimiento_cajas` add constraint `movimiento_cajas_venta_pieza_id_foreign` foreign key (`venta_pieza_id`) references `venta_piezas` (`id`) on delete set null;
create table `movimiento_cuentas` (`id` bigint unsigned not null auto_increment primary key, `entidad_id` bigint unsigned not null, `tipo` enum('Ingreso', 'Egreso') not null, `monto` decimal(12, 2) not null, `fecha` date not null, `concepto` varchar(255) null, `venta_id` bigint unsigned null, `venta_pieza_id` bigint unsigned null, `servicio_id` bigint unsigned null, `pago_id` bigint unsigned null, `user_id` bigint unsigned null, `observacion` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_entidad_id_foreign` foreign key (`entidad_id`) references `entidades` (`id`) on delete cascade;
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_venta_id_foreign` foreign key (`venta_id`) references `ventas` (`id`) on delete set null;
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_venta_pieza_id_foreign` foreign key (`venta_pieza_id`) references `venta_piezas` (`id`) on delete set null;
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_servicio_id_foreign` foreign key (`servicio_id`) references `servicios` (`id`) on delete set null;
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_pago_id_foreign` foreign key (`pago_id`) references `pagos` (`id`) on delete set null;
alter table `movimiento_cuentas` add constraint `movimiento_cuentas_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete set null;
